uploads = []
generated = []

[[outputs]]
id = "ulu0YSjDEuQsjcKaZyy8_"
uri = "file://translations.json"
type = "unspecified"
title = "ملف الترجمة — AlGhareeb Card"

[[outputs]]
id = "3hOot_c0kCAkq9I1QzmVH"
uri = "file://artifacts/alghareeb-card/public/logo.png"
type = "image"
title = "شعار القائمة والناف بار (بدون خلفية)"

[[outputs]]
id = "vnYygEqmT95PpZ1UaHmXJ"
uri = "file://artifacts/alghareeb-card/public/loading-logo.png"
type = "image"
title = "شعار شاشة التحميل (بدون خلفية)"
